[tasks.default]
dir = "{{cwd}}"
run = """
(cd aws/defn/org && mise exec -- aws s3 ls >/dev/null || mise exec -- aws sso login)
pnpm install
turbo build
b build
b test
"""
raw = true

[tools]
"npm:wrangler" = "4.61.1"
"ubi:bazelbuild/buildtools" = { version = "8.5.1", exe = "buildifier" }
"ubi:bazelbuild/bazel-watcher" = { version = "0.28.0", exe = "ibazel" }
"ubi:open-telemetry/opentelemetry-collector-releases" = { version = "0.144.0", match = "otelcol-contrib", exe = "otelcol-contrib" }
# NOTE: must sync with argocd compatibility matrix (verify when upgrading argocd)
helm = "4.0.1"
kubectl = "1.35.0"
kustomize = "5.8.0"
"ubi:charmbracelet/freeze" = "0.2.2"
"ubi:coder/agentapi" = "0.11.8"
"npm:@devcontainers/cli" = "0.82.0"
prettier = "3.8.1"
tilt = "0.36.3"
fx = "39.2.0"
terraform = "1.14.4"
steampipe = "2.3.4"
#"ubi:vectordotdev/vector" = "0.51.1"
"npm:turbo" = "2.8.1"
fd = "10.3.0"
"github:ByteNess/aws-vault" = "7.9.3"
