[tasks.default]
dir = "{{cwd}}"
run = """
(cd aws/defn/org && mise exec -- aws s3 ls >/dev/null || mise exec -- aws sso login)
pnpm install
turbo build
b build
b test
"""
raw = true

[tools]
"npm:wrangler" = "4.51.0"
"ubi:bazelbuild/buildtools" = { version = "8.2.1", exe = "buildifier" }
"ubi:bazelbuild/bazel-watcher" = { version = "0.27.0", exe = "ibazel" }
"ubi:open-telemetry/opentelemetry-collector-releases" = { version = "0.140.1", match = "otelcol-contrib", exe = "otelcol-contrib" }
helm = "4.0.1"
kubectl = "1.34.2"
kustomize = "5.8.0"
"ubi:charmbracelet/freeze" = "0.2.2"
"ubi:coder/agentapi" = "0.11.2"
"npm:@devcontainers/cli" = "0.80.2"
"npm:@google/gemini-cli" = "0.18.4"
"npm:@openai/codex" = "0.63.0"
prettier = "3.7.3"
tilt = "0.36.0"
aws-vault = "7.2.0"
fx = "39.2.0"
terraform = "1.14.0"
steampipe = "2.3.2"
"ubi:vectordotdev/vector" = "0.51.1"
"npm:turbo" = "2.6.1"
