[tasks.default]
dir = "{{cwd}}"
run = """
(cd aws/defn/org && mise exec -- aws s3 ls >/dev/null || mise exec -- aws sso login)
pnpm install
turbo build
b build
b test
"""
raw = true

[tools]
"npm:wrangler" = "4.59.2"
"ubi:bazelbuild/buildtools" = { version = "8.2.1", exe = "buildifier" }
"ubi:bazelbuild/bazel-watcher" = { version = "0.28.0", exe = "ibazel" }
"ubi:open-telemetry/opentelemetry-collector-releases" = { version = "0.143.1", match = "otelcol-contrib", exe = "otelcol-contrib" }
helm = "4.0.1"
kubectl = "1.35.0"
kustomize = "5.8.0"
"ubi:charmbracelet/freeze" = "0.2.2"
"ubi:coder/agentapi" = "0.11.8"
"npm:@devcontainers/cli" = "0.81.1"
prettier = "3.8.0"
tilt = "0.36.0"
aws-vault = "7.2.0"
fx = "39.2.0"
terraform = "1.14.3"
steampipe = "2.3.4"
#"ubi:vectordotdev/vector" = "0.51.1"
"npm:turbo" = "2.7.4"
fd = "10.3.0"
