[task_config]
dir = "tasks"

[tools]
"npm:wrangler" = "4.47.0"
"ubi:bazelbuild/buildtools" = { version = "8.2.1", exe = "buildifier" }
helm = "4.0.0"
kubectl = "1.34.2"
kustomize = "5.8.0"
"ubi:charmbracelet/freeze" = "0.2.2"
"ubi:coder/agentapi" = "0.11.0"
"npm:@devcontainers/cli" = "0.80.1"
"npm:@google/gemini-cli" = "0.14.0"
"npm:@openai/codex" = "0.57.0"
prettier = "3.6.2"
tilt = "0.35.2"
aws-vault = "7.2.0"
fx = "39.2.0"
terraform = "1.13.5"
steampipe = "2.3.2"
