[task_config]
dir = "tasks"

[tools]
"ubi:bazelbuild/buildtools" = { version = "8.2.1", exe = "buildifier" }
helm = "3.19.0"
kubectl = "1.34.1"
kustomize = "5.7.1"
"ubi:charmbracelet/freeze" = "0.2.2"
"ubi:coder/agentapi" = "0.10.2"
"npm:@devcontainers/cli" = "0.80.1"
"npm:@google/gemini-cli" = "0.11.3"
"npm:@openai/codex" = "0.53.0"
prettier = "3.6.2"
tilt = "0.35.2"
aws-vault = "7.2.0"
fx = "39.1.0"
terraform = "1.13.4"
