#ManagedBy: cue

patches: []
resources: []
helmCharts:
  - releaseName: bootstrap
    valuesInline:
      anyResources:
        kyverno: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-dfd-cluster-kyverno
            annotations:
              argocd.argoproj.io/sync-wave: "2"
          spec:
            project: default
            destination:
              name: k3d-dfd-cluster
            source:
              repoURL: https://github.com/defn/dev
              targetRevision: main
              path: m/k/r/k3d-dfd-cluster-kyverno
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions:
                - ServerSideApply=true
        cert-manager: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-dfd-cluster-cert-manager
            annotations:
              argocd.argoproj.io/sync-wave: "2"
          spec:
            project: default
            destination:
              name: k3d-dfd-cluster
            source:
              repoURL: https://github.com/defn/dev
              targetRevision: main
              path: m/k/r/k3d-dfd-cluster-cert-manager
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions: []
        trust-manager: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-dfd-cluster-trust-manager
            annotations:
              argocd.argoproj.io/sync-wave: "10"
          spec:
            project: default
            destination:
              name: k3d-dfd-cluster
            source:
              repoURL: https://github.com/defn/dev
              targetRevision: main
              path: m/k/r/k3d-dfd-cluster-trust-manager
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions: []
        pod-identity: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-dfd-cluster-pod-identity
            annotations:
              argocd.argoproj.io/sync-wave: "10"
          spec:
            project: default
            destination:
              name: k3d-dfd-cluster
            source:
              repoURL: https://github.com/defn/dev
              targetRevision: main
              path: m/k/r/k3d-dfd-cluster-pod-identity
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions: []
        external-secrets: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-dfd-cluster-external-secrets
            annotations:
              argocd.argoproj.io/sync-wave: "11"
          spec:
            project: default
            destination:
              name: k3d-dfd-cluster
            source:
              repoURL: https://github.com/defn/dev
              targetRevision: main
              path: m/k/r/k3d-dfd-cluster-external-secrets
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions: []
        secrets: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-dfd-cluster-secrets
            annotations:
              argocd.argoproj.io/sync-wave: "12"
          spec:
            project: default
            destination:
              name: k3d-dfd-cluster
            source:
              repoURL: https://github.com/defn/dev
              targetRevision: main
              path: m/k/r/k3d-dfd-cluster-secrets
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions: []
        tailscale: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-dfd-cluster-tailscale
            annotations:
              argocd.argoproj.io/sync-wave: "20"
          spec:
            project: default
            destination:
              name: k3d-dfd-cluster
            source:
              repoURL: https://github.com/defn/dev
              targetRevision: main
              path: m/k/r/k3d-dfd-cluster-tailscale
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions: []
        karpenter: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-dfd-cluster-karpenter
            annotations:
              argocd.argoproj.io/sync-wave: "20"
          spec:
            project: default
            destination:
              name: k3d-dfd-cluster
            source:
              repoURL: https://github.com/defn/dev
              targetRevision: main
              path: m/k/r/k3d-dfd-cluster-karpenter
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions: []
        tfo: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-dfd-cluster-tfo
            annotations:
              argocd.argoproj.io/sync-wave: "20"
          spec:
            project: default
            destination:
              name: k3d-dfd-cluster
            source:
              repoURL: https://github.com/defn/dev
              targetRevision: main
              path: m/k/r/k3d-dfd-cluster-tfo
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions: []
        argo-workflows: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-dfd-cluster-argo-workflows
            annotations:
              argocd.argoproj.io/sync-wave: "20"
          spec:
            project: default
            destination:
              name: k3d-dfd-cluster
            source:
              repoURL: https://github.com/defn/dev
              targetRevision: main
              path: m/k/r/k3d-dfd-cluster-argo-workflows
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions: []
        argo-events: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-dfd-cluster-argo-events
            annotations:
              argocd.argoproj.io/sync-wave: "20"
          spec:
            project: default
            destination:
              name: k3d-dfd-cluster
            source:
              repoURL: https://github.com/defn/dev
              targetRevision: main
              path: m/k/r/k3d-dfd-cluster-argo-events
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions: []
        external-dns: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-dfd-cluster-external-dns
            annotations:
              argocd.argoproj.io/sync-wave: "20"
          spec:
            project: default
            destination:
              name: k3d-dfd-cluster
            source:
              repoURL: https://github.com/defn/dev
              targetRevision: main
              path: m/k/r/k3d-dfd-cluster-external-dns
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions: []
        issuer: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-dfd-cluster-issuer
            annotations:
              argocd.argoproj.io/sync-wave: "20"
          spec:
            project: default
            destination:
              name: k3d-dfd-cluster
            source:
              repoURL: https://github.com/defn/dev
              targetRevision: main
              path: m/k/r/k3d-dfd-cluster-issuer
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions: []
        knative: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-dfd-cluster-knative
            annotations:
              argocd.argoproj.io/sync-wave: "40"
          spec:
            project: default
            destination:
              name: k3d-dfd-cluster
            source:
              repoURL: https://github.com/defn/dev
              targetRevision: main
              path: m/k/r/k3d-dfd-cluster-knative
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions: []
        kourier: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-dfd-cluster-kourier
            annotations:
              argocd.argoproj.io/sync-wave: "40"
          spec:
            project: default
            destination:
              name: k3d-dfd-cluster
            source:
              repoURL: https://github.com/defn/dev
              targetRevision: main
              path: m/k/r/k3d-dfd-cluster-kourier
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions: []
        traefik: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-dfd-cluster-traefik
            annotations:
              argocd.argoproj.io/sync-wave: "40"
          spec:
            project: default
            destination:
              name: k3d-dfd-cluster
            source:
              repoURL: https://github.com/defn/dev
              targetRevision: main
              path: m/k/r/k3d-dfd-cluster-traefik
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions: []
        headlamp: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-dfd-cluster-headlamp
            annotations:
              argocd.argoproj.io/sync-wave: "100"
          spec:
            project: default
            destination:
              name: k3d-dfd-cluster
            source:
              repoURL: https://github.com/defn/dev
              targetRevision: main
              path: m/k/r/k3d-dfd-cluster-headlamp
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions: []
        postgres-operator: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-dfd-cluster-postgres-operator
            annotations:
              argocd.argoproj.io/sync-wave: "100"
          spec:
            project: default
            destination:
              name: k3d-dfd-cluster
            source:
              repoURL: https://github.com/defn/dev
              targetRevision: main
              path: m/k/r/k3d-dfd-cluster-postgres-operator
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions: []
        coder: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-dfd-cluster-coder
            annotations:
              argocd.argoproj.io/sync-wave: "100"
          spec:
            project: default
            destination:
              name: k3d-dfd-cluster
            source:
              repoURL: https://github.com/defn/dev
              targetRevision: main
              path: m/k/r/k3d-dfd-cluster-coder
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions: []
        hello: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-dfd-cluster-hello
            annotations:
              argocd.argoproj.io/sync-wave: "100"
          spec:
            project: default
            destination:
              name: k3d-dfd-cluster
            source:
              repoURL: https://github.com/defn/dev
              targetRevision: main
              path: m/k/r/k3d-dfd-cluster-hello
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions: []
        pihole: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-dfd-cluster-pihole
            annotations:
              argocd.argoproj.io/sync-wave: "100"
          spec:
            project: default
            destination:
              name: k3d-dfd-cluster
            source:
              repoURL: https://github.com/defn/dev
              targetRevision: main
              path: m/k/r/k3d-dfd-cluster-pihole
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions: []
        dex: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-dfd-cluster-dex
            annotations:
              argocd.argoproj.io/sync-wave: "100"
          spec:
            project: default
            destination:
              name: k3d-dfd-cluster
            source:
              repoURL: https://github.com/defn/dev
              targetRevision: main
              path: m/k/r/k3d-dfd-cluster-dex
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions: []
        mastodon: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-dfd-cluster-mastodon
            annotations:
              argocd.argoproj.io/sync-wave: "100"
          spec:
            project: default
            destination:
              name: k3d-dfd-cluster
            source:
              repoURL: https://github.com/defn/dev
              targetRevision: main
              path: m/k/r/k3d-dfd-cluster-mastodon
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions: []
        cilium: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-dfd-cluster-cilium
            annotations:
              argocd.argoproj.io/sync-wave: "100"
          spec:
            project: default
            destination:
              name: k3d-dfd-cluster
            source:
              repoURL: https://github.com/defn/dev
              targetRevision: main
              path: m/k/r/k3d-dfd-cluster-cilium
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions: []
        argo-cd: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-dfd-cluster-argo-cd
            annotations:
              argocd.argoproj.io/sync-wave: "100"
          spec:
            project: default
            destination:
              name: k3d-dfd-cluster
            source:
              repoURL: https://github.com/defn/dev
              targetRevision: main
              path: m/k/r/k3d-dfd-cluster-argo-cd
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions: []
    name: any-resource
    version: 0.1.0
    repo: https://kiwigrid.github.io
    includeCRDs: true
