command_timeout = 100000

[nodejs]

disabled = true

[golang]

disabled = true

[buf]

disabled = true

[terraform]

disabled = true

[python]

disabled = true

[nix_shell]

disabled = true

[container]

disabled = true

[docker_context]

disabled = true

[cmake]

disabled = true

[custom.lockdown]
command = 'if test "$(defaults read .GlobalPreferences.plist LDMGlobalEnabled)" != "1"; then echo not-locked-down; fi'
when = ''' test "$(uname -s)" == "Darwin" '''
format = '[$output]($style) '

[custom.sip]
command = 'if ! csrutil status | grep -i ": enabled" >/dev/null; then echo sip-disabled; fi'
when = ''' test "$(uname -s)" == "Darwin" '''
format = '[$output]($style) '
