[tools]
atlas = "1.0.0"
"go:github.com/riverqueue/river/cmd/river" = "0.30.0"
"ubi:riverqueue/riverui" = "0.14.0"

[env]
DATABASE_URL = "sqlite://./river.sqlite3"
PORT = "8181"

[tasks.default]
dir = "{{cwd}}"
run = "mise run dev -- \"$@\""
raw = true
