[tools]
atlas = "0.38.0"
"go:github.com/riverqueue/river/cmd/river" = "0.28.0"
"ubi:riverqueue/riverui" = "0.13.0"

[env]
DATABASE_URL = "sqlite://./river.sqlite3"
PORT = "8181"

[tasks.default]
dir = "{{cwd}}"
run = "mise run dev -- \"$@\""
raw = true
