#ManagedBy: cue

patches:
  - path: patch-namespace-knative-serving.yaml
  - path: patch-deployment-webhook.yaml
  - path: patch-deployment-domainmappingwebhook.yaml
  - path: patch-deployment-domain-mapping.yaml
  - path: patch-deployment-controller.yaml
  - path: patch-deployment-autoscaler.yaml
  - path: patch-deployment-activator.yaml
  - path: patch-config-map-config-defaults.yaml
  - path: patch-config-map-config-domain.yaml
  - path: patch-config-map-config-features.yaml
  - path: patch-config-map-config-network.yaml
resources:
  - https://github.com/knative/serving/releases/download/knative-v1.10.0/serving-core.yaml
