[server]
port = 3001
address = "127.0.0.1"
runOnSave = true

[browser]
gatherUsageStats = false

[theme]
base = "dark"

# General color setup
textColor = "#f5f5f5"
primaryColor = "#00d492"
backgroundColor = "#1e1e1e"              # dark grey
secondaryBackgroundColor = "#2a2a2a"      # slightly lighter grey

# Widgets
showWidgetBorder = true
borderColor = "#30363d"

# Base text
font = "'Open Sans':https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap"
baseFontWeight = 400
baseFontSize = 14

# Heading text
headingFont = "'Open Sans':https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap"
headingFontWeights = [600, 300, 600]
headingFontSizes = ["3rem", "2rem", "1rem"]
