[tasks.default]
run = "set -x; ./accumulate.sh && ./configure.sh && ./unify.sh && ./transform.sh && ./execute.sh && trunk fmt && git difftool --no-prompt --extcmd='dyff between' main.yaml"
description = "Run the full ACUTE pipeline (Accumulate, Configure, Unify, Transform, Execute)"
