apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: temporal
    repo: https://temporalio.github.io/helm-charts
    version: 0.72.0
    releaseName: temporal
    namespace: temporal
    includeCRDs: true
