apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: capsule
    repo: oci://ghcr.io/projectcapsule/charts
    version: 0.12.0
    releaseName: capsule
    namespace: capsule-system
    includeCRDs: true
