apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: keda
    repo: https://kedacore.github.io/charts
    version: 2.18.1
    releaseName: keda
    namespace: keda
    includeCRDs: true
