#ManagedBy: cue

patches:
  - path: patch-service-argocd-server.yaml
  - path: patch-configmap-argocd-cm.yaml
namespace: argocd
resources:
  - resource-namespace-argocd.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.7.1/manifests/install.yaml
  - resource-ingress-argo-cd.yaml
