apiVersion: v2
description: Secure Cluster Sharing, Self-Service Namespace Provisioning and Virtual
  Clusters
home: https://loft.sh
icon: https://static.loft.sh/loft/logo/loft-logo.svg
keywords:
- developer
- development
- sharing
- share
- multi-tenancy
- tenancy
- cluster
- space
- namespace
- vcluster
- vclusters
maintainers:
- email: info@loft.sh
  name: Loft Labs, Inc.
  url: https://twitter.com/loft_sh
name: loft
sources:
- https://github.com/loft-sh/loft
type: application
version: 2.2.0
