[env]
AWS_PROFILE = "chamber-1"
AWS_REGION = "us-west-2"
AWS_CONFIG_FILE = "/home/ubuntu/m/aws/chamber/1/.aws/config"
KUBECONFIG = "${MISE_ORIGINAL_CWD}/.kube/config"

[tools]
argocd = "3.2.0"
k3d = "5.8.3"
k9s = "0.50.16"
stern = "1.33.1"
