[env]
AWS_PROFILE = "chamber-1"
AWS_REGION = "us-west-2"
AWS_CONFIG_FILE = "/home/ubuntu/m/aws/chamber/1/.aws/config"
KUBECONFIG = "/home/ubuntu/m/k3d/.kube/config"

[tools]
argocd = "3.2.1"
k3d = "5.8.3"
k9s = "0.50.16"
linkerd = "edge-25.12.1"
stern = "1.33.1"
