[env]
AWS_PROFILE = "chamber-1"
AWS_REGION = "us-west-2"
AWS_CONFIG_FILE = "/home/ubuntu/m/aws/chamber/1/.aws/config"
KUBECONFIG = "/home/ubuntu/m/k3d/.kube/config"

[tools]
argocd = "3.2.6"
# NOTE: must sync with argocd compatibility matrix (verify when upgrading argocd)
helm = "3.19.2"
k3d = "5.8.3"
k9s = "0.50.18"
linkerd = "edge-26.1.1"
node = "25.5.0"
stern = "1.33.1"
