[env]
AWS_PROFILE = "defn-org"
AWS_REGION = "us-west-2"
AWS_CONFIG_FILE = "/home/ubuntu/m/aws/defn/org/.aws/config"

[hooks]
enter = "aws sts get-caller-identity || (aws sso login && aws sts get-caller-identity)"
