#ManagedBy: cue

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: coder-wildcard
  namespace: coder
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostRegexp(`{subdomain:[a-z0-9-]+}.coder.class.amanibhavam.defn.run`)
      kind: Rule
      services:
        - name: coder
          namespace: coder
          kind: Service
          port: 80
          scheme: http
