#ManagedBy: cue

patches: []
commonLabels: {}
commonAnnotations: {}
resources: []
helmCharts:
  - releaseName: bootstrap
    valuesInline:
      anyResources:
        cert-manager-crds: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-dfd-manual-cert-manager-crds
            annotations:
              argocd.argoproj.io/sync-wave: "1"
          spec:
            project: default
            destination:
              name: k3d-dfd-manual
            source:
              repoURL: https://github.com/defn/dev
              targetRevision: main
              path: m/k/r/k3d-dfd-manual-cert-manager-crds
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions: []
        linkerd-crds: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-dfd-manual-linkerd-crds
            annotations:
              argocd.argoproj.io/sync-wave: "1"
          spec:
            project: default
            destination:
              name: k3d-dfd-manual
            source:
              repoURL: https://github.com/defn/dev
              targetRevision: main
              path: m/k/r/k3d-dfd-manual-linkerd-crds
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions: []
        cilium-bootstrap: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-dfd-manual-cilium-bootstrap
            annotations:
              argocd.argoproj.io/sync-wave: "1"
          spec:
            project: default
            destination:
              name: k3d-dfd-manual
            source:
              repoURL: https://github.com/defn/dev
              targetRevision: main
              path: m/k/r/k3d-dfd-manual-cilium-bootstrap
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions: []
    name: any-resource
    version: 0.1.0
    repo: https://kiwigrid.github.io
    includeCRDs: true
