[settings]
experimental = true

[settings.python]
compile = false

[tools]
ansible = "13.2.0"
aws = { version = "2.32.32", symlink_bins = "true" }
bat = "0.26.1"
bazelisk = "1.27.0"
chamber = "3.1.4"
coder = "2.29.1"
cue = "0.15.3"
delta = "0.18.2"
dive = "0.13.1"
dyff = "1.10.3"
fzf = "0.67.0"
gh = "2.83.2"
glow = "2.1.1"
# NOTE: must sync with go_sdk.download(version) in MODULE.bazel (rules_go)
go = "1.25.5"
gron = "0.7.1"
jq = "1.8.1"
just = "1.46.0"
node = "25.2.1"
"npm:@anthropic-ai/claude-code" = "2.1.3"
pipx = "1.8.0"
pnpm = "10.28.0"
# NOTE: must sync with python.toolchain(python_version) in MODULE.bazel (rules_python)
python = "3.13.9"
uv = "0.9.24"
shfmt = "3.12.0"
slsa-verifier = "2.7.1"
starship = "1.24.2"
"github:buildkite/agent" = { version = "3.115.3", exe = "buildkite-agent" }
"github:coder/code-server" = { version = "4.107.1", bin_path = "bin", extract_all = "true" }
"github:honeycombio/buildevents" = "0.18.0"
"github:peak/s5cmd" = "2.3.0"
watchexec = "2.3.2"
yq = "4.50.1"
gemini = "0.23.0"
bun = "1.3.5"
