[settings]
experimental = true

[settings.python]
compile = false

[tools]
ansible = "13.3.0"
aws = { version = "2.33.12", symlink_bins = "true" }
bat = "0.26.1"
bazelisk = "1.28.1"
chamber = "3.1.4"
coder = "2.29.4"
cue = "0.15.4"
delta = "0.18.2"
dive = "0.13.1"
dyff = "1.10.3"
fzf = "0.67.0"
gh = "2.86.0"
glow = "2.1.1"
# NOTE: must sync with go_sdk.download(version) in MODULE.bazel (rules_go)
go = "1.25.6"
gron = "0.7.1"
jq = "1.8.1"
just = "1.46.0"
node = "25.5.0"
pipx = "1.8.0"
pnpm = "10.28.2"
# NOTE: must sync with python.toolchain(python_version) in MODULE.bazel (rules_python)
python = "3.13.9"
# NOTE: must sync with uv version bundled in rules_uv (check uv/private/uv.lock.json)
uv = "0.8.12"
shfmt = "3.12.0"
slsa-verifier = "2.7.1"
starship = "1.24.2"
"github:buildkite/agent" = { version = "3.116.0", exe = "buildkite-agent" }
"github:honeycombio/buildevents" = "0.18.0"
"github:peak/s5cmd" = "2.3.0"
watchexec = "2.3.3"
yq = "4.52.1"
gemini = "0.26.0"
bun = "1.3.8"
"ubi:coder/code-server"= { version = "4.108.2", extract_all = "true", bin_path = "bin" }
claude = { version = "2.0.56", linux-arm64 = "" }
